### ISSUE TITLE
Fehlender Absatz in der gerenderten Ansicht nach der Überschrift "Wichtige Flags"

### ISSUE THREAD

**Issue by ColtanAkaEdoc** [PhilippEil/sw_eng_notes#15]
https://github.com/PhilippEil/sw_eng_notes/blob/8b22e6ee95128f9e4beee38c1f28abead184186e/content/console.md?plain=1#L124

Im verlinkten Source-Code ist nach "Wichtige Flags" ein Absatz, welcher in der gerenderten Ansicht nicht sichtbar ist.

**Comment by PhilippEil** [comment]
Fixt whit #21
